# Generated by Django 4.1.3 on 2022-11-23 00:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contacto_alter_article_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado el'),
            preserve_default=False,
        ),
    ]
