# Generated by Django 4.1.3 on 2022-11-23 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contacto_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='created_at',
        ),
    ]
