# Generated by Django 4.1.3 on 2022-12-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default=1, upload_to='articles', verbose_name='Imagen'),
        ),
    ]
